### ISSUE TITLE
TypeError: GenericFunASR: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by xuzhitong89** [alibaba-damo-academy/FunASR-APP#10]
windos 下 使用funasr-1.0.2  modelscope-1.11.1版本报错如下

Traceback (most recent call last):
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
           ^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\pipelines\audio\funasr_pipeline.py", line 62, in __init__
    super().__init__(model=model, **kwargs)
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\pipelines\base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
            ^^^^^^^^^^^^^^^
  File "D:\appinstall\pycharm-env\FunASR-main\Lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: GenericFunASR: 'NoneType' object is not callable

**Comment by R1ckShi** [comment]
funasr has been updated to funasr1.0 weeks ago, funasr-app is not updated accordingly, i'm working on it now
temporarily, you can install funasr v0.8.8 through source code (check out to v0.8.8 in repo https://github.com/alibaba-damo-academy/FunASR and `pip install -e ./`) and install modelscope 1.10.0
