### ISSUE TITLE
TypeError: generate() missing 1 required positional argument: 'input'

### ISSUE THREAD

**Issue by lokvke** [alibaba-damo-academy/FunASR-APP#11]
funasr == 1.0.10
modelscope == 1.12.0

-----------------------------

Traceback (most recent call last):
  File "/data/zssy-digital-human/projects/funasrapp/ClipVideo/clipvideo/videoclipper.py", line 330, in <module>
    main()
  File "/data/zssy-digital-human/projects/funasrapp/ClipVideo/clipvideo/videoclipper.py", line 326, in main
    runner(**kwargs)
  File "/data/zssy-digital-human/projects/funasrapp/ClipVideo/clipvideo/videoclipper.py", line 276, in runner
    res_text, res_srt, state = audio_clipper.recog((sr, wav), sd_switch)
  File "/data/zssy-digital-human/projects/funasrapp/ClipVideo/clipvideo/videoclipper.py", line 35, in recog
    rec_result = self.asr_pipeline(audio_in=data)
  File "/data/home/yaokj5/anaconda3/envs/geneface/lib/python3.9/site-packages/modelscope/pipelines/audio/funasr_pipeline.py", line 73, in __call__
    output = self.model(*args, **kwargs)
  File "/data/home/yaokj5/anaconda3/envs/geneface/lib/python3.9/site-packages/modelscope/models/base/base_model.py", line 35, in __call__
    return self.postprocess(self.forward(*args, **kwargs))
  File "/data/home/yaokj5/anaconda3/envs/geneface/lib/python3.9/site-packages/modelscope/models/audio/funasr/model.py", line 61, in forward
    output = self.model.generate(*args, **kwargs)
TypeError: generate() missing 1 required positional argument: 'input'

**Comment by lokvke** [comment]
i found that it is the version of funasr and modelscope make it error,  funasr==0.8.8 and modelscope==1.10.0 can solve this problem.

**Comment by 1148330040** [comment]
> i found that it is the version of funasr and modelscope make it error, funasr==0.8.8 and modelscope==1.10.0 can solve this problem.

你好，你现在运行成功了吗？我这边不报这个错误了，但是有出现了这样的问题
Traceback (most recent call last):
  File "clipvideo/videoclipper.py", line 329, in <module>
    main()
  File "clipvideo/videoclipper.py", line 325, in main
    runner(**kwargs)
  File "clipvideo/videoclipper.py", line 278, in runner
    res_text, res_srt, state = audio_clipper.video_recog(file, sd_switch)
  File "clipvideo/videoclipper.py", line 109, in video_recog
    return self.recog((16000, wav), sd_switch, state)
  File "clipvideo/videoclipper.py", line 43, in recog
    res_srt = generate_srt(rec_result['sentences'])
KeyError: 'sentences'
