### ISSUE TITLE
KeyError: 'sd_sentences' in write_state()

### ISSUE THREAD

**Issue by unboundval** [alibaba-damo-academy/FunASR-APP#9]
在写入状态的时候未检查key是否存在导致抛出异常。https://github.com/alibaba-damo-academy/FunASR-APP/blob/main/ClipVideo/clipvideo/trans_utils.py#L59
```
WARNING:root:Write total subtitile to ./output/total.srt
Traceback (most recent call last):
  File "clipvideo/videoclipper.py", line 329, in <module>
    main()
  File "clipvideo/videoclipper.py", line 325, in main
    runner(**kwargs)
  File "clipvideo/videoclipper.py", line 283, in runner
    write_state(output_dir, state)
  File "/data/playground/funasr/FunASR-APP/ClipVideo/clipvideo/trans_utils.py", line 59, in write_state
    fout.write(str(state[key[1:]]))
KeyError: 'sd_sentences'
```

**Comment by R1ckShi** [comment]
更新了相关功能，感谢反馈

**Comment by unboundval** [comment]
还有一个类似的问题在https://github.com/alibaba-damo-academy/ParaClipper/blob/main/paraclipper/trans_utils.py#L60,
在我本地运行的时候"sd_sentences"也不在state里面，导致报错.

**Comment by R1ckShi** [comment]
> 还有一个类似的问题在https://github.com/alibaba-damo-academy/ParaClipper/blob/main/paraclipper/trans_utils.py#L60, 在我本地运行的时候"sd_sentences"也不在state里面，导致报错.

本地运行是指通过命令行调用吗

**Comment by unboundval** [comment]
对，是通过命令行调用，基本上就是按照示例运行的。
```
# 步骤一：识别
python paraclipper/videoclipper.py --stage 1 \
                       --file examples/2022云栖大会_片段.mp4 \
                       --output_dir ./output
```
